/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsGet } from "../funcs/accountsGet.js";
import { accountsGetSubaccount } from "../funcs/accountsGetSubaccount.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Accounts extends ClientSDK {
  /**
   * Retrieve account details
   *
   * @remarks
   * Retrieve the current account balance and other account details. You can also check the account limit and whether the account is a **main** account. Main accounts have unrestricted privileges and, via the [User Panel](https://panel.postivo.pl), you can create as many subaccounts as needed.
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetAccountDetailsResponse> {
    return unwrapAsync(accountsGet(
      this,
      options,
    ));
  }

  /**
   * Get subaccount details
   *
   * @remarks
   * Check the account balance and other details, such as the subcredit balance of a subaccount. Subaccounts are additional users who can access your account’s services and data. You can restrict access levels and set privileges for subaccounts in the [User Panel](https://panel.postivo.pl).
   *
   * Provide the full subaccount login to access its data.
   */
  async getSubaccount(
    request: operations.GetSubaccountDetailsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSubaccountDetailsResponse> {
    return unwrapAsync(accountsGetSubaccount(
      this,
      request,
      options,
    ));
  }
}
