/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Contacts } from "./contacts.js";
import { Groups } from "./groups.js";

export class AddressBook extends ClientSDK {
  private _contacts?: Contacts;
  get contacts(): Contacts {
    return (this._contacts ??= new Contacts(this._options));
  }

  private _groups?: Groups;
  get groups(): Groups {
    return (this._groups ??= new Groups(this._options));
  }
}
