/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commonPing } from "../funcs/commonPing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Common extends ClientSDK {
  /**
   * Check API availability and version
   *
   * @remarks
   * Check the API connection and current availability status. The response also includes the current API version.
   */
  async ping(
    options?: RequestOptions,
  ): Promise<operations.PingResponse> {
    return unwrapAsync(commonPing(
      this,
      options,
    ));
  }
}
