/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Accounts } from "./accounts.js";
import { AddressBook } from "./addressbook.js";
import { Common } from "./common.js";
import { Metadata } from "./metadata.js";
import { Senders } from "./senders.js";
import { Shipments } from "./shipments.js";

export class Client extends ClientSDK {
  private _accounts?: Accounts;
  get accounts(): Accounts {
    return (this._accounts ??= new Accounts(this._options));
  }

  private _addressBook?: AddressBook;
  get addressBook(): AddressBook {
    return (this._addressBook ??= new AddressBook(this._options));
  }

  private _shipments?: Shipments;
  get shipments(): Shipments {
    return (this._shipments ??= new Shipments(this._options));
  }

  private _metadata?: Metadata;
  get metadata(): Metadata {
    return (this._metadata ??= new Metadata(this._options));
  }

  private _common?: Common;
  get common(): Common {
    return (this._common ??= new Common(this._options));
  }

  private _senders?: Senders;
  get senders(): Senders {
    return (this._senders ??= new Senders(this._options));
  }
}
