/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @postivo/postivo-client SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx shipmentsDispatch.example.ts
 */

import { Client } from "@postivo/postivo-client";

const client = new Client({
  bearer: "<YOUR API ACCESS TOKEN>",
});

async function main() {
  const result = await client.shipments.dispatch({
    recipients: {
      name: "Jan Nowak",
      name2: "Firma testowa Sp. z o.o.",
      address: "ul. Testowa",
      homeNumber: "23",
      flatNumber: "2",
      postCode: "00-999",
      city: "Warszawa",
      country: "PL",
      phoneNumber: "+48666666666",
      postscript: "Komunikat",
      customId: "1234567890",
    },
    documents: [
      {
        fileStream: "<document_1 content encoded to base64>",
        fileName: "document1.pdf",
      },
      {
        fileStream: "<document_2 content encoded to base64>",
        fileName: "document2.pdf",
      },
    ],
    options: {
      predefinedConfigId: 2670,
    },
  });

  console.log(result);
}

main().catch(console.error);
