/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddContactResponseResult =
  | models.ContactResponse
  | models.ErrorResponse;

export type AddContactResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ContactResponse | models.ErrorResponse;
};

/** @internal */
export const AddContactResponseResult$inboundSchema: z.ZodType<
  AddContactResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ContactResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function addContactResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<AddContactResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddContactResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddContactResponseResult' from JSON`,
  );
}

/** @internal */
export const AddContactResponse$inboundSchema: z.ZodType<
  AddContactResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    models.ContactResponse$inboundSchema,
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function addContactResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddContactResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddContactResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddContactResponse' from JSON`,
  );
}
