/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddContactByExtIdToGroupRequest = {
  /**
   * External (custom) ID of the contact to add to the group.
   */
  extId: string;
  /**
   * Group `id` to associate with the contact.
   */
  groupId: number;
};

export type AddContactByExtIdToGroupResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ErrorResponse | undefined;
};

/** @internal */
export type AddContactByExtIdToGroupRequest$Outbound = {
  ext_id: string;
  group_id: number;
};

/** @internal */
export const AddContactByExtIdToGroupRequest$outboundSchema: z.ZodType<
  AddContactByExtIdToGroupRequest$Outbound,
  z.ZodTypeDef,
  AddContactByExtIdToGroupRequest
> = z.object({
  extId: z.string(),
  groupId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    extId: "ext_id",
    groupId: "group_id",
  });
});

export function addContactByExtIdToGroupRequestToJSON(
  addContactByExtIdToGroupRequest: AddContactByExtIdToGroupRequest,
): string {
  return JSON.stringify(
    AddContactByExtIdToGroupRequest$outboundSchema.parse(
      addContactByExtIdToGroupRequest,
    ),
  );
}

/** @internal */
export const AddContactByExtIdToGroupResponse$inboundSchema: z.ZodType<
  AddContactByExtIdToGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ErrorResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function addContactByExtIdToGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddContactByExtIdToGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddContactByExtIdToGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddContactByExtIdToGroupResponse' from JSON`,
  );
}
