/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddContactByExtIdToGroupRequest = {
  /**
   * External (custom) ID of the contact to add to the group.
   */
  extId: string;
  /**
   * Group `id` to associate with the contact.
   */
  groupId: number;
};

export type AddContactByExtIdToGroupResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ErrorResponse;
};

/** @internal */
export const AddContactByExtIdToGroupRequest$inboundSchema: z.ZodType<
  AddContactByExtIdToGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ext_id: z.string(),
  group_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "ext_id": "extId",
    "group_id": "groupId",
  });
});

/** @internal */
export type AddContactByExtIdToGroupRequest$Outbound = {
  ext_id: string;
  group_id: number;
};

/** @internal */
export const AddContactByExtIdToGroupRequest$outboundSchema: z.ZodType<
  AddContactByExtIdToGroupRequest$Outbound,
  z.ZodTypeDef,
  AddContactByExtIdToGroupRequest
> = z.object({
  extId: z.string(),
  groupId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    extId: "ext_id",
    groupId: "group_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddContactByExtIdToGroupRequest$ {
  /** @deprecated use `AddContactByExtIdToGroupRequest$inboundSchema` instead. */
  export const inboundSchema = AddContactByExtIdToGroupRequest$inboundSchema;
  /** @deprecated use `AddContactByExtIdToGroupRequest$outboundSchema` instead. */
  export const outboundSchema = AddContactByExtIdToGroupRequest$outboundSchema;
  /** @deprecated use `AddContactByExtIdToGroupRequest$Outbound` instead. */
  export type Outbound = AddContactByExtIdToGroupRequest$Outbound;
}

export function addContactByExtIdToGroupRequestToJSON(
  addContactByExtIdToGroupRequest: AddContactByExtIdToGroupRequest,
): string {
  return JSON.stringify(
    AddContactByExtIdToGroupRequest$outboundSchema.parse(
      addContactByExtIdToGroupRequest,
    ),
  );
}

export function addContactByExtIdToGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddContactByExtIdToGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddContactByExtIdToGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddContactByExtIdToGroupRequest' from JSON`,
  );
}

/** @internal */
export const AddContactByExtIdToGroupResponse$inboundSchema: z.ZodType<
  AddContactByExtIdToGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: models.ErrorResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type AddContactByExtIdToGroupResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: models.ErrorResponse$Outbound;
};

/** @internal */
export const AddContactByExtIdToGroupResponse$outboundSchema: z.ZodType<
  AddContactByExtIdToGroupResponse$Outbound,
  z.ZodTypeDef,
  AddContactByExtIdToGroupResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: models.ErrorResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddContactByExtIdToGroupResponse$ {
  /** @deprecated use `AddContactByExtIdToGroupResponse$inboundSchema` instead. */
  export const inboundSchema = AddContactByExtIdToGroupResponse$inboundSchema;
  /** @deprecated use `AddContactByExtIdToGroupResponse$outboundSchema` instead. */
  export const outboundSchema = AddContactByExtIdToGroupResponse$outboundSchema;
  /** @deprecated use `AddContactByExtIdToGroupResponse$Outbound` instead. */
  export type Outbound = AddContactByExtIdToGroupResponse$Outbound;
}

export function addContactByExtIdToGroupResponseToJSON(
  addContactByExtIdToGroupResponse: AddContactByExtIdToGroupResponse,
): string {
  return JSON.stringify(
    AddContactByExtIdToGroupResponse$outboundSchema.parse(
      addContactByExtIdToGroupResponse,
    ),
  );
}

export function addContactByExtIdToGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddContactByExtIdToGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddContactByExtIdToGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddContactByExtIdToGroupResponse' from JSON`,
  );
}
