/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddGroupResponseResult =
  | models.GroupResponse
  | models.ErrorResponse;

export type AddGroupResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GroupResponse | models.ErrorResponse;
};

/** @internal */
export const AddGroupResponseResult$inboundSchema: z.ZodType<
  AddGroupResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.GroupResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function addGroupResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<AddGroupResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddGroupResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddGroupResponseResult' from JSON`,
  );
}

/** @internal */
export const AddGroupResponse$inboundSchema: z.ZodType<
  AddGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    models.GroupResponse$inboundSchema,
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function addGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddGroupResponse' from JSON`,
  );
}
