/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddSenderResponseResult =
  | models.SenderDetails
  | models.ErrorResponse;

export type AddSenderResponse = {
  headers: { [k: string]: Array<string> };
  result: models.SenderDetails | models.ErrorResponse;
};

/** @internal */
export const AddSenderResponseResult$inboundSchema: z.ZodType<
  AddSenderResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.SenderDetails$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function addSenderResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<AddSenderResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddSenderResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddSenderResponseResult' from JSON`,
  );
}

/** @internal */
export const AddSenderResponse$inboundSchema: z.ZodType<
  AddSenderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    models.SenderDetails$inboundSchema,
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function addSenderResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddSenderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddSenderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddSenderResponse' from JSON`,
  );
}
