/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CancelShipmentRequest = {
  /**
   * Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
   */
  ids: Array<string>;
};

export type CancelShipmentResponseResult =
  | Array<models.ShipmentCancellation>
  | models.ErrorResponse;

export type CancelShipmentResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.ShipmentCancellation> | models.ErrorResponse;
};

/** @internal */
export type CancelShipmentRequest$Outbound = {
  ids: Array<string>;
};

/** @internal */
export const CancelShipmentRequest$outboundSchema: z.ZodType<
  CancelShipmentRequest$Outbound,
  z.ZodTypeDef,
  CancelShipmentRequest
> = z.object({
  ids: z.array(z.string()),
});

export function cancelShipmentRequestToJSON(
  cancelShipmentRequest: CancelShipmentRequest,
): string {
  return JSON.stringify(
    CancelShipmentRequest$outboundSchema.parse(cancelShipmentRequest),
  );
}

/** @internal */
export const CancelShipmentResponseResult$inboundSchema: z.ZodType<
  CancelShipmentResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.ShipmentCancellation$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function cancelShipmentResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CancelShipmentResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelShipmentResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelShipmentResponseResult' from JSON`,
  );
}

/** @internal */
export const CancelShipmentResponse$inboundSchema: z.ZodType<
  CancelShipmentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.array(models.ShipmentCancellation$inboundSchema),
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function cancelShipmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelShipmentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CancelShipmentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelShipmentResponse' from JSON`,
  );
}
