/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteContactByExternalIdRequest = {
  /**
   * External (custom) ID of the contact to remove.
   */
  extId: string;
};

export type DeleteContactByExternalIdResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ErrorResponse | undefined;
};

/** @internal */
export type DeleteContactByExternalIdRequest$Outbound = {
  ext_id: string;
};

/** @internal */
export const DeleteContactByExternalIdRequest$outboundSchema: z.ZodType<
  DeleteContactByExternalIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteContactByExternalIdRequest
> = z.object({
  extId: z.string(),
}).transform((v) => {
  return remap$(v, {
    extId: "ext_id",
  });
});

export function deleteContactByExternalIdRequestToJSON(
  deleteContactByExternalIdRequest: DeleteContactByExternalIdRequest,
): string {
  return JSON.stringify(
    DeleteContactByExternalIdRequest$outboundSchema.parse(
      deleteContactByExternalIdRequest,
    ),
  );
}

/** @internal */
export const DeleteContactByExternalIdResponse$inboundSchema: z.ZodType<
  DeleteContactByExternalIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ErrorResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function deleteContactByExternalIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteContactByExternalIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteContactByExternalIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteContactByExternalIdResponse' from JSON`,
  );
}
