/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteSenderRequest = {
  /**
   * Sender `id` to remove.
   */
  id: number;
};

export type DeleteSenderResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ErrorResponse | undefined;
};

/** @internal */
export type DeleteSenderRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteSenderRequest$outboundSchema: z.ZodType<
  DeleteSenderRequest$Outbound,
  z.ZodTypeDef,
  DeleteSenderRequest
> = z.object({
  id: z.number().int(),
});

export function deleteSenderRequestToJSON(
  deleteSenderRequest: DeleteSenderRequest,
): string {
  return JSON.stringify(
    DeleteSenderRequest$outboundSchema.parse(deleteSenderRequest),
  );
}

/** @internal */
export const DeleteSenderResponse$inboundSchema: z.ZodType<
  DeleteSenderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ErrorResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function deleteSenderResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSenderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSenderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSenderResponse' from JSON`,
  );
}
