/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * How to handle contacts that belong to the group.
 */
export const ContactHandling = {
  /**
   * Detach contacts from the removed group; keep them in the Address Book.
   */
  Detach: "detach",
  /**
   * Delete the group and also remove contacts that belong only to this group.
   */
  Delete: "delete",
} as const;
/**
 * How to handle contacts that belong to the group.
 */
export type ContactHandling = ClosedEnum<typeof ContactHandling>;

export type DeleteGroupRequest = {
  /**
   * Group `id` to remove.
   */
  id: number;
  /**
   * How to handle contacts that belong to the group.
   */
  contacts?: ContactHandling | undefined;
};

export type DeleteGroupResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ErrorResponse | undefined;
};

/** @internal */
export const ContactHandling$outboundSchema: z.ZodNativeEnum<
  typeof ContactHandling
> = z.nativeEnum(ContactHandling);

/** @internal */
export type DeleteGroupRequest$Outbound = {
  id: number;
  contacts: string;
};

/** @internal */
export const DeleteGroupRequest$outboundSchema: z.ZodType<
  DeleteGroupRequest$Outbound,
  z.ZodTypeDef,
  DeleteGroupRequest
> = z.object({
  id: z.number().int(),
  contacts: ContactHandling$outboundSchema.default("detach"),
});

export function deleteGroupRequestToJSON(
  deleteGroupRequest: DeleteGroupRequest,
): string {
  return JSON.stringify(
    DeleteGroupRequest$outboundSchema.parse(deleteGroupRequest),
  );
}

/** @internal */
export const DeleteGroupResponse$inboundSchema: z.ZodType<
  DeleteGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ErrorResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function deleteGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGroupResponse' from JSON`,
  );
}
