/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAccountDetailsResponse =
  | models.AccountResponse
  | models.ErrorResponse;

/** @internal */
export const GetAccountDetailsResponse$inboundSchema: z.ZodType<
  GetAccountDetailsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.AccountResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function getAccountDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountDetailsResponse' from JSON`,
  );
}
