/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetContactByIdRequest = {
  /**
   * Global contact `id` to fetch.
   */
  id: number;
};

export type GetContactByIdResponse =
  | models.ContactResponse
  | models.ErrorResponse;

/** @internal */
export type GetContactByIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetContactByIdRequest$outboundSchema: z.ZodType<
  GetContactByIdRequest$Outbound,
  z.ZodTypeDef,
  GetContactByIdRequest
> = z.object({
  id: z.number().int(),
});

export function getContactByIdRequestToJSON(
  getContactByIdRequest: GetContactByIdRequest,
): string {
  return JSON.stringify(
    GetContactByIdRequest$outboundSchema.parse(getContactByIdRequest),
  );
}

/** @internal */
export const GetContactByIdResponse$inboundSchema: z.ZodType<
  GetContactByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ContactResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function getContactByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetContactByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactByIdResponse' from JSON`,
  );
}
