/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetContactByExternalIdRequest = {
  /**
   * External (custom) ID of the contact to fetch.
   */
  extId: string;
};

export type GetContactByExternalIdResponse =
  | models.ContactResponse
  | models.ErrorResponse;

/** @internal */
export type GetContactByExternalIdRequest$Outbound = {
  ext_id: string;
};

/** @internal */
export const GetContactByExternalIdRequest$outboundSchema: z.ZodType<
  GetContactByExternalIdRequest$Outbound,
  z.ZodTypeDef,
  GetContactByExternalIdRequest
> = z.object({
  extId: z.string(),
}).transform((v) => {
  return remap$(v, {
    extId: "ext_id",
  });
});

export function getContactByExternalIdRequestToJSON(
  getContactByExternalIdRequest: GetContactByExternalIdRequest,
): string {
  return JSON.stringify(
    GetContactByExternalIdRequest$outboundSchema.parse(
      getContactByExternalIdRequest,
    ),
  );
}

/** @internal */
export const GetContactByExternalIdResponse$inboundSchema: z.ZodType<
  GetContactByExternalIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ContactResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function getContactByExternalIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetContactByExternalIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactByExternalIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactByExternalIdResponse' from JSON`,
  );
}
