/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetSubaccountDetailsRequest = {
  /**
   * Login of the subaccount (user) for which to retrieve data.
   */
  userLogin: string;
};

export type GetSubaccountDetailsResponse =
  | models.AccountResponse
  | models.ErrorResponse;

/** @internal */
export const GetSubaccountDetailsRequest$inboundSchema: z.ZodType<
  GetSubaccountDetailsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_login: z.string(),
}).transform((v) => {
  return remap$(v, {
    "user_login": "userLogin",
  });
});

/** @internal */
export type GetSubaccountDetailsRequest$Outbound = {
  user_login: string;
};

/** @internal */
export const GetSubaccountDetailsRequest$outboundSchema: z.ZodType<
  GetSubaccountDetailsRequest$Outbound,
  z.ZodTypeDef,
  GetSubaccountDetailsRequest
> = z.object({
  userLogin: z.string(),
}).transform((v) => {
  return remap$(v, {
    userLogin: "user_login",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSubaccountDetailsRequest$ {
  /** @deprecated use `GetSubaccountDetailsRequest$inboundSchema` instead. */
  export const inboundSchema = GetSubaccountDetailsRequest$inboundSchema;
  /** @deprecated use `GetSubaccountDetailsRequest$outboundSchema` instead. */
  export const outboundSchema = GetSubaccountDetailsRequest$outboundSchema;
  /** @deprecated use `GetSubaccountDetailsRequest$Outbound` instead. */
  export type Outbound = GetSubaccountDetailsRequest$Outbound;
}

export function getSubaccountDetailsRequestToJSON(
  getSubaccountDetailsRequest: GetSubaccountDetailsRequest,
): string {
  return JSON.stringify(
    GetSubaccountDetailsRequest$outboundSchema.parse(
      getSubaccountDetailsRequest,
    ),
  );
}

export function getSubaccountDetailsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSubaccountDetailsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubaccountDetailsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubaccountDetailsRequest' from JSON`,
  );
}

/** @internal */
export const GetSubaccountDetailsResponse$inboundSchema: z.ZodType<
  GetSubaccountDetailsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.AccountResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type GetSubaccountDetailsResponse$Outbound =
  | models.AccountResponse$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const GetSubaccountDetailsResponse$outboundSchema: z.ZodType<
  GetSubaccountDetailsResponse$Outbound,
  z.ZodTypeDef,
  GetSubaccountDetailsResponse
> = z.union([
  models.AccountResponse$outboundSchema,
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSubaccountDetailsResponse$ {
  /** @deprecated use `GetSubaccountDetailsResponse$inboundSchema` instead. */
  export const inboundSchema = GetSubaccountDetailsResponse$inboundSchema;
  /** @deprecated use `GetSubaccountDetailsResponse$outboundSchema` instead. */
  export const outboundSchema = GetSubaccountDetailsResponse$outboundSchema;
  /** @deprecated use `GetSubaccountDetailsResponse$Outbound` instead. */
  export type Outbound = GetSubaccountDetailsResponse$Outbound;
}

export function getSubaccountDetailsResponseToJSON(
  getSubaccountDetailsResponse: GetSubaccountDetailsResponse,
): string {
  return JSON.stringify(
    GetSubaccountDetailsResponse$outboundSchema.parse(
      getSubaccountDetailsResponse,
    ),
  );
}

export function getSubaccountDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSubaccountDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubaccountDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubaccountDetailsResponse' from JSON`,
  );
}
