/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetStatusRequest = {
  /**
   * Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
   */
  ids: Array<string>;
};

export type GetStatusResponseResult =
  | Array<models.StatusDetails>
  | models.ErrorResponse;

export type GetStatusResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.StatusDetails> | models.ErrorResponse;
};

/** @internal */
export type GetStatusRequest$Outbound = {
  ids: Array<string>;
};

/** @internal */
export const GetStatusRequest$outboundSchema: z.ZodType<
  GetStatusRequest$Outbound,
  z.ZodTypeDef,
  GetStatusRequest
> = z.object({
  ids: z.array(z.string()),
});

export function getStatusRequestToJSON(
  getStatusRequest: GetStatusRequest,
): string {
  return JSON.stringify(
    GetStatusRequest$outboundSchema.parse(getStatusRequest),
  );
}

/** @internal */
export const GetStatusResponseResult$inboundSchema: z.ZodType<
  GetStatusResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.StatusDetails$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function getStatusResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetStatusResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStatusResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStatusResponseResult' from JSON`,
  );
}

/** @internal */
export const GetStatusResponse$inboundSchema: z.ZodType<
  GetStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.array(models.StatusDetails$inboundSchema),
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStatusResponse' from JSON`,
  );
}
