/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetSubaccountDetailsRequest = {
  /**
   * Login of the subaccount (user) for which to retrieve data.
   */
  userLogin: string;
};

export type GetSubaccountDetailsResponse =
  | models.AccountResponse
  | models.ErrorResponse;

/** @internal */
export type GetSubaccountDetailsRequest$Outbound = {
  user_login: string;
};

/** @internal */
export const GetSubaccountDetailsRequest$outboundSchema: z.ZodType<
  GetSubaccountDetailsRequest$Outbound,
  z.ZodTypeDef,
  GetSubaccountDetailsRequest
> = z.object({
  userLogin: z.string(),
}).transform((v) => {
  return remap$(v, {
    userLogin: "user_login",
  });
});

export function getSubaccountDetailsRequestToJSON(
  getSubaccountDetailsRequest: GetSubaccountDetailsRequest,
): string {
  return JSON.stringify(
    GetSubaccountDetailsRequest$outboundSchema.parse(
      getSubaccountDetailsRequest,
    ),
  );
}

/** @internal */
export const GetSubaccountDetailsResponse$inboundSchema: z.ZodType<
  GetSubaccountDetailsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.AccountResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function getSubaccountDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSubaccountDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubaccountDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubaccountDetailsResponse' from JSON`,
  );
}
