/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListSendersResponse =
  | Array<models.SenderDetails>
  | models.ErrorResponse;

/** @internal */
export const ListSendersResponse$inboundSchema: z.ZodType<
  ListSendersResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.SenderDetails$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function listSendersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSendersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSendersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSendersResponse' from JSON`,
  );
}
