/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListPredefinedConfigsResponse =
  | Array<models.PredefinedConfig>
  | models.ErrorResponse;

/** @internal */
export const ListPredefinedConfigsResponse$inboundSchema: z.ZodType<
  ListPredefinedConfigsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.PredefinedConfig$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function listPredefinedConfigsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPredefinedConfigsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPredefinedConfigsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPredefinedConfigsResponse' from JSON`,
  );
}
