/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListMetadataResponse =
  | models.MetadataResponse
  | models.ErrorResponse;

/** @internal */
export const ListMetadataResponse$inboundSchema: z.ZodType<
  ListMetadataResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.MetadataResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function listMetadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMetadataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetadataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetadataResponse' from JSON`,
  );
}
