/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListContactsRequest = {
  /**
   * Page number of results
   */
  page?: number | undefined;
  /**
   * Results limit per page.
   */
  limit?: number | undefined;
};

export type ListContactsResponseResult =
  | Array<models.ContactResponse>
  | models.ErrorResponse;

export type ListContactsResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.ContactResponse> | models.ErrorResponse;
};

/** @internal */
export type ListContactsRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const ListContactsRequest$outboundSchema: z.ZodType<
  ListContactsRequest$Outbound,
  z.ZodTypeDef,
  ListContactsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
});

export function listContactsRequestToJSON(
  listContactsRequest: ListContactsRequest,
): string {
  return JSON.stringify(
    ListContactsRequest$outboundSchema.parse(listContactsRequest),
  );
}

/** @internal */
export const ListContactsResponseResult$inboundSchema: z.ZodType<
  ListContactsResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.ContactResponse$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function listContactsResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<ListContactsResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContactsResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContactsResponseResult' from JSON`,
  );
}

/** @internal */
export const ListContactsResponse$inboundSchema: z.ZodType<
  ListContactsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.array(models.ContactResponse$inboundSchema),
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function listContactsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListContactsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContactsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContactsResponse' from JSON`,
  );
}
