/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListPredefinedConfigsResponse =
  | Array<models.PredefinedConfig>
  | models.ErrorResponse;

/** @internal */
export const ListPredefinedConfigsResponse$inboundSchema: z.ZodType<
  ListPredefinedConfigsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.PredefinedConfig$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type ListPredefinedConfigsResponse$Outbound =
  | Array<models.PredefinedConfig$Outbound>
  | models.ErrorResponse$Outbound;

/** @internal */
export const ListPredefinedConfigsResponse$outboundSchema: z.ZodType<
  ListPredefinedConfigsResponse$Outbound,
  z.ZodTypeDef,
  ListPredefinedConfigsResponse
> = z.union([
  z.array(models.PredefinedConfig$outboundSchema),
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPredefinedConfigsResponse$ {
  /** @deprecated use `ListPredefinedConfigsResponse$inboundSchema` instead. */
  export const inboundSchema = ListPredefinedConfigsResponse$inboundSchema;
  /** @deprecated use `ListPredefinedConfigsResponse$outboundSchema` instead. */
  export const outboundSchema = ListPredefinedConfigsResponse$outboundSchema;
  /** @deprecated use `ListPredefinedConfigsResponse$Outbound` instead. */
  export type Outbound = ListPredefinedConfigsResponse$Outbound;
}

export function listPredefinedConfigsResponseToJSON(
  listPredefinedConfigsResponse: ListPredefinedConfigsResponse,
): string {
  return JSON.stringify(
    ListPredefinedConfigsResponse$outboundSchema.parse(
      listPredefinedConfigsResponse,
    ),
  );
}

export function listPredefinedConfigsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPredefinedConfigsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPredefinedConfigsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPredefinedConfigsResponse' from JSON`,
  );
}
