/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListGroupsResponse =
  | Array<models.GroupResponse>
  | models.ErrorResponse;

/** @internal */
export const ListGroupsResponse$inboundSchema: z.ZodType<
  ListGroupsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.GroupResponse$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function listGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGroupsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGroupsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGroupsResponse' from JSON`,
  );
}
