/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RemoveContactByExtIdToGroupRequest = {
  /**
   * External (custom) ID of the contact to detach from the group.
   */
  extId: string;
  /**
   * Group `id` to detach from the contact.
   */
  groupId: number;
};

export type RemoveContactByExtIdToGroupResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ErrorResponse | undefined;
};

/** @internal */
export type RemoveContactByExtIdToGroupRequest$Outbound = {
  ext_id: string;
  group_id: number;
};

/** @internal */
export const RemoveContactByExtIdToGroupRequest$outboundSchema: z.ZodType<
  RemoveContactByExtIdToGroupRequest$Outbound,
  z.ZodTypeDef,
  RemoveContactByExtIdToGroupRequest
> = z.object({
  extId: z.string(),
  groupId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    extId: "ext_id",
    groupId: "group_id",
  });
});

export function removeContactByExtIdToGroupRequestToJSON(
  removeContactByExtIdToGroupRequest: RemoveContactByExtIdToGroupRequest,
): string {
  return JSON.stringify(
    RemoveContactByExtIdToGroupRequest$outboundSchema.parse(
      removeContactByExtIdToGroupRequest,
    ),
  );
}

/** @internal */
export const RemoveContactByExtIdToGroupResponse$inboundSchema: z.ZodType<
  RemoveContactByExtIdToGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ErrorResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function removeContactByExtIdToGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveContactByExtIdToGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RemoveContactByExtIdToGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveContactByExtIdToGroupResponse' from JSON`,
  );
}
