/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RemoveContactFromGroupRequest = {
  /**
   * Global contact `id` to detach from the group.
   */
  id: number;
  /**
   * Group `id` to detach from the contact.
   */
  groupId: number;
};

export type RemoveContactFromGroupResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ErrorResponse | undefined;
};

/** @internal */
export type RemoveContactFromGroupRequest$Outbound = {
  id: number;
  group_id: number;
};

/** @internal */
export const RemoveContactFromGroupRequest$outboundSchema: z.ZodType<
  RemoveContactFromGroupRequest$Outbound,
  z.ZodTypeDef,
  RemoveContactFromGroupRequest
> = z.object({
  id: z.number().int(),
  groupId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    groupId: "group_id",
  });
});

export function removeContactFromGroupRequestToJSON(
  removeContactFromGroupRequest: RemoveContactFromGroupRequest,
): string {
  return JSON.stringify(
    RemoveContactFromGroupRequest$outboundSchema.parse(
      removeContactFromGroupRequest,
    ),
  );
}

/** @internal */
export const RemoveContactFromGroupResponse$inboundSchema: z.ZodType<
  RemoveContactFromGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ErrorResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function removeContactFromGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveContactFromGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveContactFromGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveContactFromGroupResponse' from JSON`,
  );
}
