/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ShipmentPriceResponseResult =
  | Array<models.ShipmentPrice>
  | models.ErrorResponse;

export type ShipmentPriceResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.ShipmentPrice> | models.ErrorResponse;
};

/** @internal */
export const ShipmentPriceResponseResult$inboundSchema: z.ZodType<
  ShipmentPriceResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.ShipmentPrice$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function shipmentPriceResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<ShipmentPriceResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShipmentPriceResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShipmentPriceResponseResult' from JSON`,
  );
}

/** @internal */
export const ShipmentPriceResponse$inboundSchema: z.ZodType<
  ShipmentPriceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.array(models.ShipmentPrice$inboundSchema),
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function shipmentPriceResponseFromJSON(
  jsonString: string,
): SafeParseResult<ShipmentPriceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShipmentPriceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShipmentPriceResponse' from JSON`,
  );
}
