/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ShipmentDispatchResponseResult =
  | Array<models.ShipmentDetails>
  | models.ErrorResponse;

export type ShipmentDispatchResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.ShipmentDetails> | models.ErrorResponse;
};

/** @internal */
export const ShipmentDispatchResponseResult$inboundSchema: z.ZodType<
  ShipmentDispatchResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(models.ShipmentDetails$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

export function shipmentDispatchResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<ShipmentDispatchResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShipmentDispatchResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShipmentDispatchResponseResult' from JSON`,
  );
}

/** @internal */
export const ShipmentDispatchResponse$inboundSchema: z.ZodType<
  ShipmentDispatchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.array(models.ShipmentDetails$inboundSchema),
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function shipmentDispatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<ShipmentDispatchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShipmentDispatchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShipmentDispatchResponse' from JSON`,
  );
}
