/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateContactRequest = {
  /**
   * ID of the contact to update.
   */
  id: number;
  /**
   * A `Contact` object with the updated fields.
   */
  contact: models.Contact;
};

export type UpdateContactResponseResult =
  | models.ContactResponse
  | models.ErrorResponse;

export type UpdateContactResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ContactResponse | models.ErrorResponse;
};

/** @internal */
export type UpdateContactRequest$Outbound = {
  id: number;
  Contact: models.Contact$Outbound;
};

/** @internal */
export const UpdateContactRequest$outboundSchema: z.ZodType<
  UpdateContactRequest$Outbound,
  z.ZodTypeDef,
  UpdateContactRequest
> = z.object({
  id: z.number().int(),
  contact: models.Contact$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    contact: "Contact",
  });
});

export function updateContactRequestToJSON(
  updateContactRequest: UpdateContactRequest,
): string {
  return JSON.stringify(
    UpdateContactRequest$outboundSchema.parse(updateContactRequest),
  );
}

/** @internal */
export const UpdateContactResponseResult$inboundSchema: z.ZodType<
  UpdateContactResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ContactResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function updateContactResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<UpdateContactResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateContactResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateContactResponseResult' from JSON`,
  );
}

/** @internal */
export const UpdateContactResponse$inboundSchema: z.ZodType<
  UpdateContactResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    models.ContactResponse$inboundSchema,
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function updateContactResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateContactResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateContactResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateContactResponse' from JSON`,
  );
}
