/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateGroupRequest = {
  /**
   * Group `id` to update.
   */
  id: number;
  /**
   * A `Group` object with the updated fields.
   */
  group: models.Group;
};

export type UpdateGroupResponseResult =
  | models.GroupResponse
  | models.ErrorResponse;

export type UpdateGroupResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GroupResponse | models.ErrorResponse;
};

/** @internal */
export type UpdateGroupRequest$Outbound = {
  id: number;
  Group: models.Group$Outbound;
};

/** @internal */
export const UpdateGroupRequest$outboundSchema: z.ZodType<
  UpdateGroupRequest$Outbound,
  z.ZodTypeDef,
  UpdateGroupRequest
> = z.object({
  id: z.number().int(),
  group: models.Group$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    group: "Group",
  });
});

export function updateGroupRequestToJSON(
  updateGroupRequest: UpdateGroupRequest,
): string {
  return JSON.stringify(
    UpdateGroupRequest$outboundSchema.parse(updateGroupRequest),
  );
}

/** @internal */
export const UpdateGroupResponseResult$inboundSchema: z.ZodType<
  UpdateGroupResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.GroupResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function updateGroupResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<UpdateGroupResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateGroupResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateGroupResponseResult' from JSON`,
  );
}

/** @internal */
export const UpdateGroupResponse$inboundSchema: z.ZodType<
  UpdateGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    models.GroupResponse$inboundSchema,
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function updateGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateGroupResponse' from JSON`,
  );
}
