/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateContactByExternalIdRequest = {
  /**
   * External (custom) ID of the contact to update.
   */
  extId: string;
  /**
   * A `Contact` object with the updated fields.
   */
  contact: models.Contact;
};

export type UpdateContactByExternalIdResponseResult =
  | models.ContactResponse
  | models.ErrorResponse;

export type UpdateContactByExternalIdResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ContactResponse | models.ErrorResponse;
};

/** @internal */
export type UpdateContactByExternalIdRequest$Outbound = {
  ext_id: string;
  Contact: models.Contact$Outbound;
};

/** @internal */
export const UpdateContactByExternalIdRequest$outboundSchema: z.ZodType<
  UpdateContactByExternalIdRequest$Outbound,
  z.ZodTypeDef,
  UpdateContactByExternalIdRequest
> = z.object({
  extId: z.string(),
  contact: models.Contact$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    extId: "ext_id",
    contact: "Contact",
  });
});

export function updateContactByExternalIdRequestToJSON(
  updateContactByExternalIdRequest: UpdateContactByExternalIdRequest,
): string {
  return JSON.stringify(
    UpdateContactByExternalIdRequest$outboundSchema.parse(
      updateContactByExternalIdRequest,
    ),
  );
}

/** @internal */
export const UpdateContactByExternalIdResponseResult$inboundSchema: z.ZodType<
  UpdateContactByExternalIdResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ContactResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

export function updateContactByExternalIdResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateContactByExternalIdResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateContactByExternalIdResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateContactByExternalIdResponseResult' from JSON`,
  );
}

/** @internal */
export const UpdateContactByExternalIdResponse$inboundSchema: z.ZodType<
  UpdateContactByExternalIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    models.ContactResponse$inboundSchema,
    models.ErrorResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function updateContactByExternalIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateContactByExternalIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateContactByExternalIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateContactByExternalIdResponse' from JSON`,
  );
}
