/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Account type.
 */
export const AccountType = {
  /**
   * Account type PRE-PAID
   */
  PrePaid: "PRE-PAID",
  /**
   * Account type POST-PAID
   */
  PostPaid: "POST-PAID",
} as const;
/**
 * Account type.
 */
export type AccountType = ClosedEnum<typeof AccountType>;

/**
 * Account details, including balance and limits.
 */
export type AccountResponse = {
  /**
   * User login.
   */
  login?: string | undefined;
  /**
   * Account type.
   */
  accountType?: AccountType | undefined;
  /**
   * Account limit.
   */
  limit?: number | undefined;
  /**
   * Current account balance.
   */
  credit?: number | undefined;
  /**
   * Subaccount credit balance; null if unlimited.
   */
  subcredit?: number | null | undefined;
  /**
   * Account currency.
   */
  currency?: string | undefined;
  /**
   * User full name.
   */
  name?: string | undefined;
  /**
   * Indicates whether this is the main account.
   */
  isMain?: boolean | undefined;
};

/** @internal */
export const AccountType$inboundSchema: z.ZodNativeEnum<typeof AccountType> = z
  .nativeEnum(AccountType);

/** @internal */
export const AccountResponse$inboundSchema: z.ZodType<
  AccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  login: z.string().optional(),
  account_type: AccountType$inboundSchema.optional(),
  limit: z.number().optional(),
  credit: z.number().optional(),
  subcredit: z.nullable(z.number()).optional(),
  currency: z.string().optional(),
  name: z.string().optional(),
  is_main: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "account_type": "accountType",
    "is_main": "isMain",
  });
});

export function accountResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountResponse' from JSON`,
  );
}
