/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  DocumentLibrary,
  DocumentLibrary$Outbound,
  DocumentLibrary$outboundSchema,
} from "./documentlibrary.js";
import {
  DocumentMock,
  DocumentMock$Outbound,
  DocumentMock$outboundSchema,
} from "./documentmock.js";
import {
  DocumentPdf,
  DocumentPdf$Outbound,
  DocumentPdf$outboundSchema,
} from "./documentpdf.js";

/**
 * A base document object.
 */
export type Documents = DocumentPdf | DocumentLibrary | DocumentMock;

/** @internal */
export type Documents$Outbound =
  | DocumentPdf$Outbound
  | DocumentLibrary$Outbound
  | DocumentMock$Outbound;

/** @internal */
export const Documents$outboundSchema: z.ZodType<
  Documents$Outbound,
  z.ZodTypeDef,
  Documents
> = z.union([
  DocumentPdf$outboundSchema,
  DocumentLibrary$outboundSchema,
  DocumentMock$outboundSchema,
]);

export function documentsToJSON(documents: Documents): string {
  return JSON.stringify(Documents$outboundSchema.parse(documents));
}
