/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * A document from the user's account library.
 */
export type DocumentLibrary = {
  /**
   * ID of the document stored in the user’s document library.
   */
  id: number;
};

/** @internal */
export type DocumentLibrary$Outbound = {
  id: number;
};

/** @internal */
export const DocumentLibrary$outboundSchema: z.ZodType<
  DocumentLibrary$Outbound,
  z.ZodTypeDef,
  DocumentLibrary
> = z.object({
  id: z.number().int(),
});

export function documentLibraryToJSON(
  documentLibrary: DocumentLibrary,
): string {
  return JSON.stringify(DocumentLibrary$outboundSchema.parse(documentLibrary));
}
