/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Mock document used to simulate page count for pricing without uploading a real file.
 */
export type DocumentMock = {
  /**
   * Number of pages in the mock document.
   */
  pages: number;
};

/** @internal */
export type DocumentMock$Outbound = {
  pages: number;
};

/** @internal */
export const DocumentMock$outboundSchema: z.ZodType<
  DocumentMock$Outbound,
  z.ZodTypeDef,
  DocumentMock
> = z.object({
  pages: z.number().int(),
});

export function documentMockToJSON(documentMock: DocumentMock): string {
  return JSON.stringify(DocumentMock$outboundSchema.parse(documentMock));
}
