/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * PDF document payload.
 */
export type DocumentPdf = {
  /**
   * Base64-encoded PDF content.
   */
  fileStream: string;
  /**
   * Optional file name for identification purposes.
   */
  fileName?: string | null | undefined;
};

/** @internal */
export type DocumentPdf$Outbound = {
  file_stream: string;
  file_name: string | null;
};

/** @internal */
export const DocumentPdf$outboundSchema: z.ZodType<
  DocumentPdf$Outbound,
  z.ZodTypeDef,
  DocumentPdf
> = z.object({
  fileStream: z.string(),
  fileName: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    fileStream: "file_stream",
    fileName: "file_name",
  });
});

export function documentPdfToJSON(documentPdf: DocumentPdf): string {
  return JSON.stringify(DocumentPdf$outboundSchema.parse(documentPdf));
}
