/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Address Book group details returned by the API.
 */
export type GroupResponse = {
  /**
   * Group name.
   */
  name: string;
  /**
   * Optional group description.
   */
  description?: string | null | undefined;
  /**
   * Unique system-assigned group ID.
   */
  id: number;
  /**
   * Indicates whether the group data was inherited from a main account’s shared Address Book.
   */
  inherited?: boolean | undefined;
};

/** @internal */
export const GroupResponse$inboundSchema: z.ZodType<
  GroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  id: z.number().int(),
  inherited: z.boolean().optional(),
});

export function groupResponseFromJSON(
  jsonString: string,
): SafeParseResult<GroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupResponse' from JSON`,
  );
}
