/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Contact group definition in the Address Book.
 */
export type Group = {
  /**
   * Group name.
   */
  name: string;
  /**
   * Optional group description.
   */
  description?: string | null | undefined;
};

/** @internal */
export type Group$Outbound = {
  name: string;
  description?: string | null | undefined;
};

/** @internal */
export const Group$outboundSchema: z.ZodType<
  Group$Outbound,
  z.ZodTypeDef,
  Group
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
});

export function groupToJSON(group: Group): string {
  return JSON.stringify(Group$outboundSchema.parse(group));
}
