/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Ping response.
 */
export type PingResponse = {
  /**
   * API service status: OK (available), ERR (unavailable).
   */
  status?: string | undefined;
  /**
   * Current API version.
   */
  version?: string | undefined;
  /**
   * Indicates whether the connection was established to the test system (SANDBOX).
   */
  sandbox?: boolean | undefined;
};

/** @internal */
export const PingResponse$inboundSchema: z.ZodType<
  PingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string().optional(),
  version: z.string().optional(),
  sandbox: z.boolean().optional(),
});

export function pingResponseFromJSON(
  jsonString: string,
): SafeParseResult<PingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PingResponse' from JSON`,
  );
}
