/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Select recipient data for a shipment from the Address Book.
 */
export type RecipientFromAddressBook = {
  /**
   * Global ID of the recipient stored in the personal Address Book.
   */
  id: number;
  /**
   * User-assigned custom shipment ID.
   */
  customId?: string | null | undefined;
  /**
   * Optional postscript printed above the recipient data on the envelope.
   */
  postscript?: string | null | undefined;
};

/** @internal */
export type RecipientFromAddressBook$Outbound = {
  id: number;
  custom_id: string | null;
  postscript?: string | null | undefined;
};

/** @internal */
export const RecipientFromAddressBook$outboundSchema: z.ZodType<
  RecipientFromAddressBook$Outbound,
  z.ZodTypeDef,
  RecipientFromAddressBook
> = z.object({
  id: z.number().int(),
  customId: z.nullable(z.string()).default(null),
  postscript: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    customId: "custom_id",
  });
});

export function recipientFromAddressBookToJSON(
  recipientFromAddressBook: RecipientFromAddressBook,
): string {
  return JSON.stringify(
    RecipientFromAddressBook$outboundSchema.parse(recipientFromAddressBook),
  );
}
