/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  RecipientFromAddressBook,
  RecipientFromAddressBook$Outbound,
  RecipientFromAddressBook$outboundSchema,
} from "./recipientfromaddressbook.js";
import {
  RecipientFromAddressBookByExternalId,
  RecipientFromAddressBookByExternalId$Outbound,
  RecipientFromAddressBookByExternalId$outboundSchema,
} from "./recipientfromaddressbookbyexternalid.js";
import {
  RecipientInline,
  RecipientInline$Outbound,
  RecipientInline$outboundSchema,
} from "./recipientinline.js";

/**
 * A base recipient object.
 */
export type Recipients =
  | RecipientInline
  | RecipientFromAddressBook
  | RecipientFromAddressBookByExternalId;

/** @internal */
export type Recipients$Outbound =
  | RecipientInline$Outbound
  | RecipientFromAddressBook$Outbound
  | RecipientFromAddressBookByExternalId$Outbound;

/** @internal */
export const Recipients$outboundSchema: z.ZodType<
  Recipients$Outbound,
  z.ZodTypeDef,
  Recipients
> = z.union([
  RecipientInline$outboundSchema,
  RecipientFromAddressBook$outboundSchema,
  RecipientFromAddressBookByExternalId$outboundSchema,
]);

export function recipientsToJSON(recipients: Recipients): string {
  return JSON.stringify(Recipients$outboundSchema.parse(recipients));
}
