/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Sender, Sender$inboundSchema } from "./sender.js";

/**
 * Extended sender details.
 */
export type SenderDetails = {
  /**
   * Unique sender ID.
   */
  id?: number | undefined;
  /**
   * Sender data for the shipment.
   */
  sender: Sender;
  /**
   * Indicates whether the sender is active.
   */
  active: boolean;
  /**
   * Indicates whether this is the default sender.
   */
  default: boolean;
};

/** @internal */
export const SenderDetails$inboundSchema: z.ZodType<
  SenderDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  sender: Sender$inboundSchema,
  active: z.boolean(),
  default: z.boolean(),
});

export function senderDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SenderDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SenderDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SenderDetails' from JSON`,
  );
}
