/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "./errorresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Result of cancelling a single shipment
 */
export type ShipmentCancellation = {
  /**
   * Shipment ID.
   */
  id?: string | undefined;
  /**
   * Cancellation status code (`204` if cancelled successfully; otherwise an error code).
   */
  status?: number | undefined;
  /**
   * Problem Details object (RFC 9457) describing the error.
   */
  error?: ErrorResponse | null | undefined;
};

/** @internal */
export const ShipmentCancellation$inboundSchema: z.ZodType<
  ShipmentCancellation,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  status: z.number().int().optional(),
  error: z.nullable(ErrorResponse$inboundSchema).optional(),
});

export function shipmentCancellationFromJSON(
  jsonString: string,
): SafeParseResult<ShipmentCancellation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShipmentCancellation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShipmentCancellation' from JSON`,
  );
}
