/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import {
  DocumentLibrary,
  DocumentLibrary$inboundSchema,
  DocumentLibrary$Outbound,
  DocumentLibrary$outboundSchema,
} from "./documentlibrary.js";
import {
  DocumentMock,
  DocumentMock$inboundSchema,
  DocumentMock$Outbound,
  DocumentMock$outboundSchema,
} from "./documentmock.js";
import {
  DocumentPdf,
  DocumentPdf$inboundSchema,
  DocumentPdf$Outbound,
  DocumentPdf$outboundSchema,
} from "./documentpdf.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  RecipientFromAddressBook,
  RecipientFromAddressBook$inboundSchema,
  RecipientFromAddressBook$Outbound,
  RecipientFromAddressBook$outboundSchema,
} from "./recipientfromaddressbook.js";
import {
  RecipientFromAddressBookByExternalId,
  RecipientFromAddressBookByExternalId$inboundSchema,
  RecipientFromAddressBookByExternalId$Outbound,
  RecipientFromAddressBookByExternalId$outboundSchema,
} from "./recipientfromaddressbookbyexternalid.js";
import {
  RecipientInline,
  RecipientInline$inboundSchema,
  RecipientInline$Outbound,
  RecipientInline$outboundSchema,
} from "./recipientinline.js";

export type Recipients1 =
  | RecipientInline
  | RecipientFromAddressBook
  | RecipientFromAddressBookByExternalId;

/**
 * Recipient data for a single shipment. For one recipient, provide a `RecipientInline`, `RecipientFromAddressBook`, or `RecipientFromAddressBookByExternalId` object. For multiple recipients, provide an array of these objects (1–50).
 */
export type Recipients2 =
  | RecipientInline
  | RecipientFromAddressBook
  | RecipientFromAddressBookByExternalId
  | Array<
    | RecipientInline
    | RecipientFromAddressBook
    | RecipientFromAddressBookByExternalId
  >;

export type Documents1 = DocumentPdf | DocumentLibrary | DocumentMock;

/**
 * Document payload to print and enclose. For a single document, provide `DocumentPdf` or `DocumentLibrary`. For multiple documents, provide an array of `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` objects (1–20).
 */
export type Documents2 =
  | DocumentPdf
  | DocumentLibrary
  | DocumentMock
  | Array<DocumentPdf | DocumentLibrary | DocumentMock>;

/**
 * Shipment configuration parameters. Overrides settings loaded from `predefined_config_id`.
 */
export type InlineConfig = {
  /**
   * Preferred carrier identifier.
   */
  carrierId: number;
  /**
   * Preferred service identifier (shipment type).
   */
  serviceId: number;
  /**
   * Preferred paper type identifier.
   */
  paperId?: number | undefined;
  /**
   * Print documents in color (`true`) or grayscale (`false`).
   */
  colorPrint?: boolean | undefined;
  /**
   * Print documents duplex (`true`) or single-sided (`false`).
   */
  duplexPrint?: boolean | undefined;
  /**
   * Preferred envelope size/template identifier defined in the user account.
   */
  envelopeId?: number | undefined;
  /**
   * Print the envelope in color (`true`) or grayscale (`false`).
   */
  envelopeColorPrint?: boolean | undefined;
};

export type InlineConfigUnion = InlineConfig;

/**
 * Per-shipment callback configuration. When set, overrides the global callback defined in the user account.
 */
export type Callback = {
  /**
   * Callback target URL.
   */
  url: string;
  /**
   * Bearer token to include in callback requests for authentication.
   */
  userToken?: string | null | undefined;
};

export type CallbackUnion = Callback;

/**
 * Additional shipment metadata. At least one of `order_name` or `mpk` must be provided.
 */
export type MiscInfo = {
  /**
   * MPK (“miejsce powstania kosztu”) — billing cost-center identifier to be included on invoices.
   */
  mpk?: string | null | undefined;
  /**
   * Order name assigned to this shipment; displayed in reports and related views.
   */
  orderName?: string | null | undefined;
};

export type MiscInfoUnion = MiscInfo;

/**
 * Additional shipment settings.
 */
export type RequestOptions = {
  /**
   * ID of the shipment configuration profile stored in the user account.
   */
  predefinedConfigId?: number | null | undefined;
  inlineConfig?: InlineConfig | null | undefined;
  /**
   * ID of the sender stored in the user account.
   */
  senderId?: number | null | undefined;
  /**
   * Scheduled dispatch date (ISO 8601).
   */
  dispatchDate?: RFCDate | undefined;
  callback?: Callback | null | undefined;
  miscInfo?: MiscInfo | null | undefined;
  /**
   * If true, rotate all documents 180° before printing (barcodes will be printed on opposite margins).
   */
  rotateDocuments?: boolean | undefined;
};

export type Options = RequestOptions;

/**
 * Properties of a new shipment.
 */
export type Shipment = {
  /**
   * Recipient data for a single shipment. For one recipient, provide a `RecipientInline`, `RecipientFromAddressBook`, or `RecipientFromAddressBookByExternalId` object. For multiple recipients, provide an array of these objects (1–50).
   */
  recipients:
    | RecipientInline
    | RecipientFromAddressBook
    | RecipientFromAddressBookByExternalId
    | Array<
      | RecipientInline
      | RecipientFromAddressBook
      | RecipientFromAddressBookByExternalId
    >;
  /**
   * Document payload to print and enclose. For a single document, provide `DocumentPdf` or `DocumentLibrary`. For multiple documents, provide an array of `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` objects (1–20).
   */
  documents:
    | DocumentPdf
    | DocumentLibrary
    | DocumentMock
    | Array<DocumentPdf | DocumentLibrary | DocumentMock>;
  options?: RequestOptions | null | undefined;
};

/** @internal */
export const Recipients1$inboundSchema: z.ZodType<
  Recipients1,
  z.ZodTypeDef,
  unknown
> = z.union([
  RecipientInline$inboundSchema,
  RecipientFromAddressBook$inboundSchema,
  RecipientFromAddressBookByExternalId$inboundSchema,
]);

/** @internal */
export type Recipients1$Outbound =
  | RecipientInline$Outbound
  | RecipientFromAddressBook$Outbound
  | RecipientFromAddressBookByExternalId$Outbound;

/** @internal */
export const Recipients1$outboundSchema: z.ZodType<
  Recipients1$Outbound,
  z.ZodTypeDef,
  Recipients1
> = z.union([
  RecipientInline$outboundSchema,
  RecipientFromAddressBook$outboundSchema,
  RecipientFromAddressBookByExternalId$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Recipients1$ {
  /** @deprecated use `Recipients1$inboundSchema` instead. */
  export const inboundSchema = Recipients1$inboundSchema;
  /** @deprecated use `Recipients1$outboundSchema` instead. */
  export const outboundSchema = Recipients1$outboundSchema;
  /** @deprecated use `Recipients1$Outbound` instead. */
  export type Outbound = Recipients1$Outbound;
}

export function recipients1ToJSON(recipients1: Recipients1): string {
  return JSON.stringify(Recipients1$outboundSchema.parse(recipients1));
}

export function recipients1FromJSON(
  jsonString: string,
): SafeParseResult<Recipients1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Recipients1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Recipients1' from JSON`,
  );
}

/** @internal */
export const Recipients2$inboundSchema: z.ZodType<
  Recipients2,
  z.ZodTypeDef,
  unknown
> = z.union([
  RecipientInline$inboundSchema,
  RecipientFromAddressBook$inboundSchema,
  RecipientFromAddressBookByExternalId$inboundSchema,
  z.array(
    z.union([
      RecipientInline$inboundSchema,
      RecipientFromAddressBook$inboundSchema,
      RecipientFromAddressBookByExternalId$inboundSchema,
    ]),
  ),
]);

/** @internal */
export type Recipients2$Outbound =
  | RecipientInline$Outbound
  | RecipientFromAddressBook$Outbound
  | RecipientFromAddressBookByExternalId$Outbound
  | Array<
    | RecipientInline$Outbound
    | RecipientFromAddressBook$Outbound
    | RecipientFromAddressBookByExternalId$Outbound
  >;

/** @internal */
export const Recipients2$outboundSchema: z.ZodType<
  Recipients2$Outbound,
  z.ZodTypeDef,
  Recipients2
> = z.union([
  RecipientInline$outboundSchema,
  RecipientFromAddressBook$outboundSchema,
  RecipientFromAddressBookByExternalId$outboundSchema,
  z.array(
    z.union([
      RecipientInline$outboundSchema,
      RecipientFromAddressBook$outboundSchema,
      RecipientFromAddressBookByExternalId$outboundSchema,
    ]),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Recipients2$ {
  /** @deprecated use `Recipients2$inboundSchema` instead. */
  export const inboundSchema = Recipients2$inboundSchema;
  /** @deprecated use `Recipients2$outboundSchema` instead. */
  export const outboundSchema = Recipients2$outboundSchema;
  /** @deprecated use `Recipients2$Outbound` instead. */
  export type Outbound = Recipients2$Outbound;
}

export function recipients2ToJSON(recipients2: Recipients2): string {
  return JSON.stringify(Recipients2$outboundSchema.parse(recipients2));
}

export function recipients2FromJSON(
  jsonString: string,
): SafeParseResult<Recipients2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Recipients2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Recipients2' from JSON`,
  );
}

/** @internal */
export const Documents1$inboundSchema: z.ZodType<
  Documents1,
  z.ZodTypeDef,
  unknown
> = z.union([
  DocumentPdf$inboundSchema,
  DocumentLibrary$inboundSchema,
  DocumentMock$inboundSchema,
]);

/** @internal */
export type Documents1$Outbound =
  | DocumentPdf$Outbound
  | DocumentLibrary$Outbound
  | DocumentMock$Outbound;

/** @internal */
export const Documents1$outboundSchema: z.ZodType<
  Documents1$Outbound,
  z.ZodTypeDef,
  Documents1
> = z.union([
  DocumentPdf$outboundSchema,
  DocumentLibrary$outboundSchema,
  DocumentMock$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Documents1$ {
  /** @deprecated use `Documents1$inboundSchema` instead. */
  export const inboundSchema = Documents1$inboundSchema;
  /** @deprecated use `Documents1$outboundSchema` instead. */
  export const outboundSchema = Documents1$outboundSchema;
  /** @deprecated use `Documents1$Outbound` instead. */
  export type Outbound = Documents1$Outbound;
}

export function documents1ToJSON(documents1: Documents1): string {
  return JSON.stringify(Documents1$outboundSchema.parse(documents1));
}

export function documents1FromJSON(
  jsonString: string,
): SafeParseResult<Documents1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Documents1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Documents1' from JSON`,
  );
}

/** @internal */
export const Documents2$inboundSchema: z.ZodType<
  Documents2,
  z.ZodTypeDef,
  unknown
> = z.union([
  DocumentPdf$inboundSchema,
  DocumentLibrary$inboundSchema,
  DocumentMock$inboundSchema,
  z.array(
    z.union([
      DocumentPdf$inboundSchema,
      DocumentLibrary$inboundSchema,
      DocumentMock$inboundSchema,
    ]),
  ),
]);

/** @internal */
export type Documents2$Outbound =
  | DocumentPdf$Outbound
  | DocumentLibrary$Outbound
  | DocumentMock$Outbound
  | Array<
    DocumentPdf$Outbound | DocumentLibrary$Outbound | DocumentMock$Outbound
  >;

/** @internal */
export const Documents2$outboundSchema: z.ZodType<
  Documents2$Outbound,
  z.ZodTypeDef,
  Documents2
> = z.union([
  DocumentPdf$outboundSchema,
  DocumentLibrary$outboundSchema,
  DocumentMock$outboundSchema,
  z.array(
    z.union([
      DocumentPdf$outboundSchema,
      DocumentLibrary$outboundSchema,
      DocumentMock$outboundSchema,
    ]),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Documents2$ {
  /** @deprecated use `Documents2$inboundSchema` instead. */
  export const inboundSchema = Documents2$inboundSchema;
  /** @deprecated use `Documents2$outboundSchema` instead. */
  export const outboundSchema = Documents2$outboundSchema;
  /** @deprecated use `Documents2$Outbound` instead. */
  export type Outbound = Documents2$Outbound;
}

export function documents2ToJSON(documents2: Documents2): string {
  return JSON.stringify(Documents2$outboundSchema.parse(documents2));
}

export function documents2FromJSON(
  jsonString: string,
): SafeParseResult<Documents2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Documents2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Documents2' from JSON`,
  );
}

/** @internal */
export const InlineConfig$inboundSchema: z.ZodType<
  InlineConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  carrier_id: z.number().int(),
  service_id: z.number().int(),
  paper_id: z.number().int().optional(),
  color_print: z.boolean().optional(),
  duplex_print: z.boolean().optional(),
  envelope_id: z.number().int().optional(),
  envelope_color_print: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "carrier_id": "carrierId",
    "service_id": "serviceId",
    "paper_id": "paperId",
    "color_print": "colorPrint",
    "duplex_print": "duplexPrint",
    "envelope_id": "envelopeId",
    "envelope_color_print": "envelopeColorPrint",
  });
});

/** @internal */
export type InlineConfig$Outbound = {
  carrier_id: number;
  service_id: number;
  paper_id?: number | undefined;
  color_print?: boolean | undefined;
  duplex_print?: boolean | undefined;
  envelope_id?: number | undefined;
  envelope_color_print?: boolean | undefined;
};

/** @internal */
export const InlineConfig$outboundSchema: z.ZodType<
  InlineConfig$Outbound,
  z.ZodTypeDef,
  InlineConfig
> = z.object({
  carrierId: z.number().int(),
  serviceId: z.number().int(),
  paperId: z.number().int().optional(),
  colorPrint: z.boolean().optional(),
  duplexPrint: z.boolean().optional(),
  envelopeId: z.number().int().optional(),
  envelopeColorPrint: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    carrierId: "carrier_id",
    serviceId: "service_id",
    paperId: "paper_id",
    colorPrint: "color_print",
    duplexPrint: "duplex_print",
    envelopeId: "envelope_id",
    envelopeColorPrint: "envelope_color_print",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InlineConfig$ {
  /** @deprecated use `InlineConfig$inboundSchema` instead. */
  export const inboundSchema = InlineConfig$inboundSchema;
  /** @deprecated use `InlineConfig$outboundSchema` instead. */
  export const outboundSchema = InlineConfig$outboundSchema;
  /** @deprecated use `InlineConfig$Outbound` instead. */
  export type Outbound = InlineConfig$Outbound;
}

export function inlineConfigToJSON(inlineConfig: InlineConfig): string {
  return JSON.stringify(InlineConfig$outboundSchema.parse(inlineConfig));
}

export function inlineConfigFromJSON(
  jsonString: string,
): SafeParseResult<InlineConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InlineConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InlineConfig' from JSON`,
  );
}

/** @internal */
export const InlineConfigUnion$inboundSchema: z.ZodType<
  InlineConfigUnion,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => InlineConfig$inboundSchema);

/** @internal */
export type InlineConfigUnion$Outbound = InlineConfig$Outbound;

/** @internal */
export const InlineConfigUnion$outboundSchema: z.ZodType<
  InlineConfigUnion$Outbound,
  z.ZodTypeDef,
  InlineConfigUnion
> = z.lazy(() => InlineConfig$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InlineConfigUnion$ {
  /** @deprecated use `InlineConfigUnion$inboundSchema` instead. */
  export const inboundSchema = InlineConfigUnion$inboundSchema;
  /** @deprecated use `InlineConfigUnion$outboundSchema` instead. */
  export const outboundSchema = InlineConfigUnion$outboundSchema;
  /** @deprecated use `InlineConfigUnion$Outbound` instead. */
  export type Outbound = InlineConfigUnion$Outbound;
}

export function inlineConfigUnionToJSON(
  inlineConfigUnion: InlineConfigUnion,
): string {
  return JSON.stringify(
    InlineConfigUnion$outboundSchema.parse(inlineConfigUnion),
  );
}

export function inlineConfigUnionFromJSON(
  jsonString: string,
): SafeParseResult<InlineConfigUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InlineConfigUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InlineConfigUnion' from JSON`,
  );
}

/** @internal */
export const Callback$inboundSchema: z.ZodType<
  Callback,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  user_token: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    "user_token": "userToken",
  });
});

/** @internal */
export type Callback$Outbound = {
  url: string;
  user_token: string | null;
};

/** @internal */
export const Callback$outboundSchema: z.ZodType<
  Callback$Outbound,
  z.ZodTypeDef,
  Callback
> = z.object({
  url: z.string(),
  userToken: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    userToken: "user_token",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Callback$ {
  /** @deprecated use `Callback$inboundSchema` instead. */
  export const inboundSchema = Callback$inboundSchema;
  /** @deprecated use `Callback$outboundSchema` instead. */
  export const outboundSchema = Callback$outboundSchema;
  /** @deprecated use `Callback$Outbound` instead. */
  export type Outbound = Callback$Outbound;
}

export function callbackToJSON(callback: Callback): string {
  return JSON.stringify(Callback$outboundSchema.parse(callback));
}

export function callbackFromJSON(
  jsonString: string,
): SafeParseResult<Callback, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Callback$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Callback' from JSON`,
  );
}

/** @internal */
export const CallbackUnion$inboundSchema: z.ZodType<
  CallbackUnion,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => Callback$inboundSchema);

/** @internal */
export type CallbackUnion$Outbound = Callback$Outbound;

/** @internal */
export const CallbackUnion$outboundSchema: z.ZodType<
  CallbackUnion$Outbound,
  z.ZodTypeDef,
  CallbackUnion
> = z.lazy(() => Callback$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CallbackUnion$ {
  /** @deprecated use `CallbackUnion$inboundSchema` instead. */
  export const inboundSchema = CallbackUnion$inboundSchema;
  /** @deprecated use `CallbackUnion$outboundSchema` instead. */
  export const outboundSchema = CallbackUnion$outboundSchema;
  /** @deprecated use `CallbackUnion$Outbound` instead. */
  export type Outbound = CallbackUnion$Outbound;
}

export function callbackUnionToJSON(callbackUnion: CallbackUnion): string {
  return JSON.stringify(CallbackUnion$outboundSchema.parse(callbackUnion));
}

export function callbackUnionFromJSON(
  jsonString: string,
): SafeParseResult<CallbackUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CallbackUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CallbackUnion' from JSON`,
  );
}

/** @internal */
export const MiscInfo$inboundSchema: z.ZodType<
  MiscInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  mpk: z.nullable(z.string()).default(null),
  order_name: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    "order_name": "orderName",
  });
});

/** @internal */
export type MiscInfo$Outbound = {
  mpk: string | null;
  order_name: string | null;
};

/** @internal */
export const MiscInfo$outboundSchema: z.ZodType<
  MiscInfo$Outbound,
  z.ZodTypeDef,
  MiscInfo
> = z.object({
  mpk: z.nullable(z.string()).default(null),
  orderName: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    orderName: "order_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MiscInfo$ {
  /** @deprecated use `MiscInfo$inboundSchema` instead. */
  export const inboundSchema = MiscInfo$inboundSchema;
  /** @deprecated use `MiscInfo$outboundSchema` instead. */
  export const outboundSchema = MiscInfo$outboundSchema;
  /** @deprecated use `MiscInfo$Outbound` instead. */
  export type Outbound = MiscInfo$Outbound;
}

export function miscInfoToJSON(miscInfo: MiscInfo): string {
  return JSON.stringify(MiscInfo$outboundSchema.parse(miscInfo));
}

export function miscInfoFromJSON(
  jsonString: string,
): SafeParseResult<MiscInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MiscInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MiscInfo' from JSON`,
  );
}

/** @internal */
export const MiscInfoUnion$inboundSchema: z.ZodType<
  MiscInfoUnion,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => MiscInfo$inboundSchema);

/** @internal */
export type MiscInfoUnion$Outbound = MiscInfo$Outbound;

/** @internal */
export const MiscInfoUnion$outboundSchema: z.ZodType<
  MiscInfoUnion$Outbound,
  z.ZodTypeDef,
  MiscInfoUnion
> = z.lazy(() => MiscInfo$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MiscInfoUnion$ {
  /** @deprecated use `MiscInfoUnion$inboundSchema` instead. */
  export const inboundSchema = MiscInfoUnion$inboundSchema;
  /** @deprecated use `MiscInfoUnion$outboundSchema` instead. */
  export const outboundSchema = MiscInfoUnion$outboundSchema;
  /** @deprecated use `MiscInfoUnion$Outbound` instead. */
  export type Outbound = MiscInfoUnion$Outbound;
}

export function miscInfoUnionToJSON(miscInfoUnion: MiscInfoUnion): string {
  return JSON.stringify(MiscInfoUnion$outboundSchema.parse(miscInfoUnion));
}

export function miscInfoUnionFromJSON(
  jsonString: string,
): SafeParseResult<MiscInfoUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MiscInfoUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MiscInfoUnion' from JSON`,
  );
}

/** @internal */
export const RequestOptions$inboundSchema: z.ZodType<
  RequestOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  predefined_config_id: z.nullable(z.number().int()).optional(),
  inline_config: z.nullable(z.lazy(() => InlineConfig$inboundSchema))
    .optional(),
  sender_id: z.nullable(z.number().int()).optional(),
  dispatch_date: z.string().transform(v => new RFCDate(v)).optional(),
  callback: z.nullable(z.lazy(() => Callback$inboundSchema)).optional(),
  misc_info: z.nullable(z.lazy(() => MiscInfo$inboundSchema)).optional(),
  rotate_documents: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "predefined_config_id": "predefinedConfigId",
    "inline_config": "inlineConfig",
    "sender_id": "senderId",
    "dispatch_date": "dispatchDate",
    "misc_info": "miscInfo",
    "rotate_documents": "rotateDocuments",
  });
});

/** @internal */
export type RequestOptions$Outbound = {
  predefined_config_id?: number | null | undefined;
  inline_config?: InlineConfig$Outbound | null | undefined;
  sender_id?: number | null | undefined;
  dispatch_date?: string | undefined;
  callback?: Callback$Outbound | null | undefined;
  misc_info?: MiscInfo$Outbound | null | undefined;
  rotate_documents?: boolean | undefined;
};

/** @internal */
export const RequestOptions$outboundSchema: z.ZodType<
  RequestOptions$Outbound,
  z.ZodTypeDef,
  RequestOptions
> = z.object({
  predefinedConfigId: z.nullable(z.number().int()).optional(),
  inlineConfig: z.nullable(z.lazy(() => InlineConfig$outboundSchema))
    .optional(),
  senderId: z.nullable(z.number().int()).optional(),
  dispatchDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  callback: z.nullable(z.lazy(() => Callback$outboundSchema)).optional(),
  miscInfo: z.nullable(z.lazy(() => MiscInfo$outboundSchema)).optional(),
  rotateDocuments: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    predefinedConfigId: "predefined_config_id",
    inlineConfig: "inline_config",
    senderId: "sender_id",
    dispatchDate: "dispatch_date",
    miscInfo: "misc_info",
    rotateDocuments: "rotate_documents",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RequestOptions$ {
  /** @deprecated use `RequestOptions$inboundSchema` instead. */
  export const inboundSchema = RequestOptions$inboundSchema;
  /** @deprecated use `RequestOptions$outboundSchema` instead. */
  export const outboundSchema = RequestOptions$outboundSchema;
  /** @deprecated use `RequestOptions$Outbound` instead. */
  export type Outbound = RequestOptions$Outbound;
}

export function requestOptionsToJSON(requestOptions: RequestOptions): string {
  return JSON.stringify(RequestOptions$outboundSchema.parse(requestOptions));
}

export function requestOptionsFromJSON(
  jsonString: string,
): SafeParseResult<RequestOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RequestOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequestOptions' from JSON`,
  );
}

/** @internal */
export const Options$inboundSchema: z.ZodType<Options, z.ZodTypeDef, unknown> =
  z.lazy(() => RequestOptions$inboundSchema);

/** @internal */
export type Options$Outbound = RequestOptions$Outbound;

/** @internal */
export const Options$outboundSchema: z.ZodType<
  Options$Outbound,
  z.ZodTypeDef,
  Options
> = z.lazy(() => RequestOptions$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Options$ {
  /** @deprecated use `Options$inboundSchema` instead. */
  export const inboundSchema = Options$inboundSchema;
  /** @deprecated use `Options$outboundSchema` instead. */
  export const outboundSchema = Options$outboundSchema;
  /** @deprecated use `Options$Outbound` instead. */
  export type Outbound = Options$Outbound;
}

export function optionsToJSON(options: Options): string {
  return JSON.stringify(Options$outboundSchema.parse(options));
}

export function optionsFromJSON(
  jsonString: string,
): SafeParseResult<Options, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Options$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Options' from JSON`,
  );
}

/** @internal */
export const Shipment$inboundSchema: z.ZodType<
  Shipment,
  z.ZodTypeDef,
  unknown
> = z.object({
  recipients: z.union([
    RecipientInline$inboundSchema,
    RecipientFromAddressBook$inboundSchema,
    RecipientFromAddressBookByExternalId$inboundSchema,
    z.array(
      z.union([
        RecipientInline$inboundSchema,
        RecipientFromAddressBook$inboundSchema,
        RecipientFromAddressBookByExternalId$inboundSchema,
      ]),
    ),
  ]),
  documents: z.union([
    DocumentPdf$inboundSchema,
    DocumentLibrary$inboundSchema,
    DocumentMock$inboundSchema,
    z.array(
      z.union([
        DocumentPdf$inboundSchema,
        DocumentLibrary$inboundSchema,
        DocumentMock$inboundSchema,
      ]),
    ),
  ]),
  options: z.nullable(z.lazy(() => RequestOptions$inboundSchema)).optional(),
});

/** @internal */
export type Shipment$Outbound = {
  recipients:
    | RecipientInline$Outbound
    | RecipientFromAddressBook$Outbound
    | RecipientFromAddressBookByExternalId$Outbound
    | Array<
      | RecipientInline$Outbound
      | RecipientFromAddressBook$Outbound
      | RecipientFromAddressBookByExternalId$Outbound
    >;
  documents:
    | DocumentPdf$Outbound
    | DocumentLibrary$Outbound
    | DocumentMock$Outbound
    | Array<
      DocumentPdf$Outbound | DocumentLibrary$Outbound | DocumentMock$Outbound
    >;
  options?: RequestOptions$Outbound | null | undefined;
};

/** @internal */
export const Shipment$outboundSchema: z.ZodType<
  Shipment$Outbound,
  z.ZodTypeDef,
  Shipment
> = z.object({
  recipients: z.union([
    RecipientInline$outboundSchema,
    RecipientFromAddressBook$outboundSchema,
    RecipientFromAddressBookByExternalId$outboundSchema,
    z.array(
      z.union([
        RecipientInline$outboundSchema,
        RecipientFromAddressBook$outboundSchema,
        RecipientFromAddressBookByExternalId$outboundSchema,
      ]),
    ),
  ]),
  documents: z.union([
    DocumentPdf$outboundSchema,
    DocumentLibrary$outboundSchema,
    DocumentMock$outboundSchema,
    z.array(
      z.union([
        DocumentPdf$outboundSchema,
        DocumentLibrary$outboundSchema,
        DocumentMock$outboundSchema,
      ]),
    ),
  ]),
  options: z.nullable(z.lazy(() => RequestOptions$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Shipment$ {
  /** @deprecated use `Shipment$inboundSchema` instead. */
  export const inboundSchema = Shipment$inboundSchema;
  /** @deprecated use `Shipment$outboundSchema` instead. */
  export const outboundSchema = Shipment$outboundSchema;
  /** @deprecated use `Shipment$Outbound` instead. */
  export type Outbound = Shipment$Outbound;
}

export function shipmentToJSON(shipment: Shipment): string {
  return JSON.stringify(Shipment$outboundSchema.parse(shipment));
}

export function shipmentFromJSON(
  jsonString: string,
): SafeParseResult<Shipment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Shipment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Shipment' from JSON`,
  );
}
