/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { RFCDate } from "../types/rfcdate.js";
import {
  Documents,
  Documents$Outbound,
  Documents$outboundSchema,
} from "./documents.js";
import {
  Recipients,
  Recipients$Outbound,
  Recipients$outboundSchema,
} from "./recipients.js";

/**
 * Recipient data for a single shipment. For one recipient, provide a `RecipientInline`, `RecipientFromAddressBook`, or `RecipientFromAddressBookByExternalId` object. For multiple recipients, provide an array of these objects (1–50).
 */
export type ShipmentRecipients = Recipients | Array<Recipients>;

/**
 * Document payload to print and enclose into shipment. For a single document, provide `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` (for checking the price only). For multiple documents, provide an array of `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` objects (1–20).
 */
export type ShipmentDocuments = Documents | Array<Documents>;

/**
 * Shipment configuration parameters. Overrides settings loaded from `predefined_config_id`.
 */
export type InlineConfig = {
  /**
   * Preferred carrier identifier.
   */
  carrierId: number;
  /**
   * Preferred service identifier (shipment type).
   */
  serviceId: number;
  /**
   * Preferred paper type identifier.
   */
  paperId?: number | undefined;
  /**
   * Print documents in color (`true`) or grayscale (`false`).
   */
  colorPrint?: boolean | undefined;
  /**
   * Print documents duplex (`true`) or single-sided (`false`).
   */
  duplexPrint?: boolean | undefined;
  /**
   * Preferred envelope size/template identifier defined in the user account.
   */
  envelopeId?: number | undefined;
  /**
   * Print the envelope in color (`true`) or grayscale (`false`).
   */
  envelopeColorPrint?: boolean | undefined;
};

export type InlineConfigUnion = InlineConfig;

/**
 * Per-shipment callback configuration. When set, overrides the global callback defined in the user account.
 */
export type Callback = {
  /**
   * Callback target URL.
   */
  url: string;
  /**
   * Bearer token to include in callback requests for authentication.
   */
  userToken?: string | null | undefined;
};

export type CallbackUnion = Callback;

/**
 * Additional shipment metadata. At least one of `order_name` or `mpk` must be provided.
 */
export type MiscInfo = {
  /**
   * MPK (“miejsce powstania kosztu”) — billing cost-center identifier to be included on invoices.
   */
  mpk?: string | null | undefined;
  /**
   * Order name assigned to this shipment; displayed in reports and related views.
   */
  orderName?: string | null | undefined;
};

export type MiscInfoUnion = MiscInfo;

/**
 * Additional shipment settings.
 */
export type ShipmentOptions = {
  /**
   * ID of the shipment configuration profile stored in the user account.
   */
  predefinedConfigId?: number | null | undefined;
  inlineConfig?: InlineConfig | null | undefined;
  /**
   * ID of the sender stored in the user account.
   */
  senderId?: number | null | undefined;
  /**
   * Scheduled dispatch date (ISO 8601).
   */
  dispatchDate?: RFCDate | undefined;
  callback?: Callback | null | undefined;
  miscInfo?: MiscInfo | null | undefined;
  /**
   * If true, rotate all documents 180° before printing (barcodes will be printed on opposite margins).
   */
  rotateDocuments?: boolean | undefined;
};

export type Options = ShipmentOptions;

/**
 * Properties of a new shipment.
 */
export type Shipment = {
  /**
   * Recipient data for a single shipment. For one recipient, provide a `RecipientInline`, `RecipientFromAddressBook`, or `RecipientFromAddressBookByExternalId` object. For multiple recipients, provide an array of these objects (1–50).
   */
  recipients: Recipients | Array<Recipients>;
  /**
   * Document payload to print and enclose into shipment. For a single document, provide `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` (for checking the price only). For multiple documents, provide an array of `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` objects (1–20).
   */
  documents: Documents | Array<Documents>;
  options?: ShipmentOptions | null | undefined;
};

/** @internal */
export type ShipmentRecipients$Outbound =
  | Recipients$Outbound
  | Array<Recipients$Outbound>;

/** @internal */
export const ShipmentRecipients$outboundSchema: z.ZodType<
  ShipmentRecipients$Outbound,
  z.ZodTypeDef,
  ShipmentRecipients
> = z.union([
  Recipients$outboundSchema,
  z.array(z.lazy(() => Recipients$outboundSchema)),
]);

export function shipmentRecipientsToJSON(
  shipmentRecipients: ShipmentRecipients,
): string {
  return JSON.stringify(
    ShipmentRecipients$outboundSchema.parse(shipmentRecipients),
  );
}

/** @internal */
export type ShipmentDocuments$Outbound =
  | Documents$Outbound
  | Array<Documents$Outbound>;

/** @internal */
export const ShipmentDocuments$outboundSchema: z.ZodType<
  ShipmentDocuments$Outbound,
  z.ZodTypeDef,
  ShipmentDocuments
> = z.union([
  Documents$outboundSchema,
  z.array(z.lazy(() => Documents$outboundSchema)),
]);

export function shipmentDocumentsToJSON(
  shipmentDocuments: ShipmentDocuments,
): string {
  return JSON.stringify(
    ShipmentDocuments$outboundSchema.parse(shipmentDocuments),
  );
}

/** @internal */
export type InlineConfig$Outbound = {
  carrier_id: number;
  service_id: number;
  paper_id?: number | undefined;
  color_print?: boolean | undefined;
  duplex_print?: boolean | undefined;
  envelope_id?: number | undefined;
  envelope_color_print?: boolean | undefined;
};

/** @internal */
export const InlineConfig$outboundSchema: z.ZodType<
  InlineConfig$Outbound,
  z.ZodTypeDef,
  InlineConfig
> = z.object({
  carrierId: z.number().int(),
  serviceId: z.number().int(),
  paperId: z.number().int().optional(),
  colorPrint: z.boolean().optional(),
  duplexPrint: z.boolean().optional(),
  envelopeId: z.number().int().optional(),
  envelopeColorPrint: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    carrierId: "carrier_id",
    serviceId: "service_id",
    paperId: "paper_id",
    colorPrint: "color_print",
    duplexPrint: "duplex_print",
    envelopeId: "envelope_id",
    envelopeColorPrint: "envelope_color_print",
  });
});

export function inlineConfigToJSON(inlineConfig: InlineConfig): string {
  return JSON.stringify(InlineConfig$outboundSchema.parse(inlineConfig));
}

/** @internal */
export type InlineConfigUnion$Outbound = InlineConfig$Outbound;

/** @internal */
export const InlineConfigUnion$outboundSchema: z.ZodType<
  InlineConfigUnion$Outbound,
  z.ZodTypeDef,
  InlineConfigUnion
> = z.lazy(() => InlineConfig$outboundSchema);

export function inlineConfigUnionToJSON(
  inlineConfigUnion: InlineConfigUnion,
): string {
  return JSON.stringify(
    InlineConfigUnion$outboundSchema.parse(inlineConfigUnion),
  );
}

/** @internal */
export type Callback$Outbound = {
  url: string;
  user_token: string | null;
};

/** @internal */
export const Callback$outboundSchema: z.ZodType<
  Callback$Outbound,
  z.ZodTypeDef,
  Callback
> = z.object({
  url: z.string(),
  userToken: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    userToken: "user_token",
  });
});

export function callbackToJSON(callback: Callback): string {
  return JSON.stringify(Callback$outboundSchema.parse(callback));
}

/** @internal */
export type CallbackUnion$Outbound = Callback$Outbound;

/** @internal */
export const CallbackUnion$outboundSchema: z.ZodType<
  CallbackUnion$Outbound,
  z.ZodTypeDef,
  CallbackUnion
> = z.lazy(() => Callback$outboundSchema);

export function callbackUnionToJSON(callbackUnion: CallbackUnion): string {
  return JSON.stringify(CallbackUnion$outboundSchema.parse(callbackUnion));
}

/** @internal */
export type MiscInfo$Outbound = {
  mpk: string | null;
  order_name: string | null;
};

/** @internal */
export const MiscInfo$outboundSchema: z.ZodType<
  MiscInfo$Outbound,
  z.ZodTypeDef,
  MiscInfo
> = z.object({
  mpk: z.nullable(z.string()).default(null),
  orderName: z.nullable(z.string()).default(null),
}).transform((v) => {
  return remap$(v, {
    orderName: "order_name",
  });
});

export function miscInfoToJSON(miscInfo: MiscInfo): string {
  return JSON.stringify(MiscInfo$outboundSchema.parse(miscInfo));
}

/** @internal */
export type MiscInfoUnion$Outbound = MiscInfo$Outbound;

/** @internal */
export const MiscInfoUnion$outboundSchema: z.ZodType<
  MiscInfoUnion$Outbound,
  z.ZodTypeDef,
  MiscInfoUnion
> = z.lazy(() => MiscInfo$outboundSchema);

export function miscInfoUnionToJSON(miscInfoUnion: MiscInfoUnion): string {
  return JSON.stringify(MiscInfoUnion$outboundSchema.parse(miscInfoUnion));
}

/** @internal */
export type ShipmentOptions$Outbound = {
  predefined_config_id?: number | null | undefined;
  inline_config?: InlineConfig$Outbound | null | undefined;
  sender_id?: number | null | undefined;
  dispatch_date?: string | undefined;
  callback?: Callback$Outbound | null | undefined;
  misc_info?: MiscInfo$Outbound | null | undefined;
  rotate_documents?: boolean | undefined;
};

/** @internal */
export const ShipmentOptions$outboundSchema: z.ZodType<
  ShipmentOptions$Outbound,
  z.ZodTypeDef,
  ShipmentOptions
> = z.object({
  predefinedConfigId: z.nullable(z.number().int()).optional(),
  inlineConfig: z.nullable(z.lazy(() => InlineConfig$outboundSchema))
    .optional(),
  senderId: z.nullable(z.number().int()).optional(),
  dispatchDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  callback: z.nullable(z.lazy(() => Callback$outboundSchema)).optional(),
  miscInfo: z.nullable(z.lazy(() => MiscInfo$outboundSchema)).optional(),
  rotateDocuments: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    predefinedConfigId: "predefined_config_id",
    inlineConfig: "inline_config",
    senderId: "sender_id",
    dispatchDate: "dispatch_date",
    miscInfo: "misc_info",
    rotateDocuments: "rotate_documents",
  });
});

export function shipmentOptionsToJSON(
  shipmentOptions: ShipmentOptions,
): string {
  return JSON.stringify(ShipmentOptions$outboundSchema.parse(shipmentOptions));
}

/** @internal */
export type Options$Outbound = ShipmentOptions$Outbound;

/** @internal */
export const Options$outboundSchema: z.ZodType<
  Options$Outbound,
  z.ZodTypeDef,
  Options
> = z.lazy(() => ShipmentOptions$outboundSchema);

export function optionsToJSON(options: Options): string {
  return JSON.stringify(Options$outboundSchema.parse(options));
}

/** @internal */
export type Shipment$Outbound = {
  recipients: Recipients$Outbound | Array<Recipients$Outbound>;
  documents: Documents$Outbound | Array<Documents$Outbound>;
  options?: ShipmentOptions$Outbound | null | undefined;
};

/** @internal */
export const Shipment$outboundSchema: z.ZodType<
  Shipment$Outbound,
  z.ZodTypeDef,
  Shipment
> = z.object({
  recipients: z.union([
    Recipients$outboundSchema,
    z.array(z.lazy(() => Recipients$outboundSchema)),
  ]),
  documents: z.union([
    Documents$outboundSchema,
    z.array(z.lazy(() => Documents$outboundSchema)),
  ]),
  options: z.nullable(z.lazy(() => ShipmentOptions$outboundSchema)).optional(),
});

export function shipmentToJSON(shipment: Shipment): string {
  return JSON.stringify(Shipment$outboundSchema.parse(shipment));
}
