/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ShipmentDetails,
  ShipmentDetails$inboundSchema,
} from "./shipmentdetails.js";
import { StatusEvent, StatusEvent$inboundSchema } from "./statusevent.js";

/**
 * Details of a single shipment and its status events
 */
export type StatusDetails = {
  /**
   * Single shipment details
   */
  shipmentDetails?: ShipmentDetails | undefined;
  /**
   * List of status events for the shipment.
   */
  statusEvents?: Array<StatusEvent> | null | undefined;
};

/** @internal */
export const StatusDetails$inboundSchema: z.ZodType<
  StatusDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  shipment_details: ShipmentDetails$inboundSchema.optional(),
  status_events: z.nullable(z.array(StatusEvent$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "shipment_details": "shipmentDetails",
    "status_events": "statusEvents",
  });
});

export function statusDetailsFromJSON(
  jsonString: string,
): SafeParseResult<StatusDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusDetails' from JSON`,
  );
}
